// src/utils/courierData.ts

export interface CourierService {
  id: string;
  company: string;
  serviceName: string;
  type: "domestic" | "international";
  originCountry: string;
  supportedRoutes: string[];
  features: {
    tracking: boolean;
    insurance: boolean;
    pickup: boolean;
  };
  deliveryDays: {
    min: number;
    max: number;
  };
  reliabilityScore: number;
  tags: string[];

  // Pricing coefficients for mockup calculation
  baseRate: number;                  // local currency (domestic) or USD (international)
  perAdditionalHalfKgRate: number;   // local currency (domestic) or USD (international)
  distanceRate: number;              // local currency (domestic) or USD (international)
  maxWeightAllowed: number;          // in kg
}

export const COURIER_SERVICES: CourierService[] = [
  // ================= US COURIERS =================
  {
    id: "ups-ground-us",
    company: "UPS",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.3,
    tags: ["most_reliable", "business_friendly"],
    baseRate: 13.80,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.55,
    maxWeightAllowed: 70
  },
  {
    id: "ups-3-day-select",
    company: "UPS",
    serviceName: "3 Day Select",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.4,
    tags: ["reliable"],
    baseRate: 22.50,
    perAdditionalHalfKgRate: 2.80,
    distanceRate: 0.75,
    maxWeightAllowed: 70
  },
  {
    id: "ups-next-day-air",
    company: "UPS",
    serviceName: "Next Day Air",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.8,
    tags: ["fastest", "premium"],
    baseRate: 38.00,
    perAdditionalHalfKgRate: 4.80,
    distanceRate: 1.20,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-ground-us",
    company: "FedEx",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.2,
    tags: ["best_value", "business_friendly"],
    baseRate: 14.50,
    perAdditionalHalfKgRate: 2.10,
    distanceRate: 0.60,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-home-delivery",
    company: "FedEx",
    serviceName: "Home Delivery",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.1,
    tags: ["ecommerce_friendly"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 2.15,
    distanceRate: 0.65,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-express-saver",
    company: "FedEx",
    serviceName: "Express Saver",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 3 },
    reliabilityScore: 9.3,
    tags: ["reliable"],
    baseRate: 24.00,
    perAdditionalHalfKgRate: 3.10,
    distanceRate: 0.85,
    maxWeightAllowed: 70
  },
  {
    id: "usps-ground-advantage",
    company: "USPS",
    serviceName: "Ground Advantage",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 6.20,
    perAdditionalHalfKgRate: 1.10,
    distanceRate: 0.30,
    maxWeightAllowed: 30
  },
  {
    id: "usps-priority-mail",
    company: "USPS",
    serviceName: "Priority Mail",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 8.8,
    tags: ["best_value"],
    baseRate: 9.20,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "usps-priority-mail-express",
    company: "USPS",
    serviceName: "Priority Mail Express",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.0,
    tags: ["fastest"],
    baseRate: 28.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.00,
    maxWeightAllowed: 30
  },
  {
    id: "ontrac-regional-us",
    company: "OnTrac",
    serviceName: "Regional Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.2,
    tags: ["fastest", "ecommerce_friendly", "regional_specialist"],
    baseRate: 11.50,
    perAdditionalHalfKgRate: 1.60,
    distanceRate: 0.50,
    maxWeightAllowed: 70
  },
  {
    id: "lso-regional-tx",
    company: "LSO",
    serviceName: "Regional",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.3,
    tags: ["ecommerce_friendly", "regional_specialist"],
    baseRate: 7.50,
    perAdditionalHalfKgRate: 0.55,
    distanceRate: 0.50,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-ecommerce-us",
    company: "DHL",
    serviceName: "eCommerce",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 3, max: 8 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 5.80,
    perAdditionalHalfKgRate: 1.00,
    distanceRate: 0.28,
    maxWeightAllowed: 25
  },
  {
    id: "dhl-express-worldwide-us",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-saver",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["fastest", "business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-expedited",
    company: "UPS",
    serviceName: "Worldwide Expedited",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.3,
    tags: ["reliable"],
    baseRate: 18.00,
    perAdditionalHalfKgRate: 6.20,
    distanceRate: 2.00,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-priority",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["fastest", "premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-economy",
    company: "FedEx",
    serviceName: "International Economy",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 4, max: 6 },
    reliabilityScore: 9.0,
    tags: ["best_value"],
    baseRate: 16.50,
    perAdditionalHalfKgRate: 5.80,
    distanceRate: 1.80,
    maxWeightAllowed: 300
  },
  {
    id: "usps-priority-intl",
    company: "USPS",
    serviceName: "Priority Mail International",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 10 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.20,
    maxWeightAllowed: 30
  },
  {
    id: "usps-express-mail-intl",
    company: "USPS",
    serviceName: "Express Mail International",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 3, max: 5 },
    reliabilityScore: 8.2,
    tags: ["best_value"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 5.00,
    distanceRate: 1.60,
    maxWeightAllowed: 30
  },

  // ================= GB COURIERS =================
  {
    id: "royal-mail-tracked-24",
    company: "Royal Mail",
    serviceName: "Tracked 24",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.8,
    tags: ["fastest", "student_friendly"],
    baseRate: 4.80,
    perAdditionalHalfKgRate: 1.10,
    distanceRate: 0.25,
    maxWeightAllowed: 20
  },
  {
    id: "royal-mail-tracked-48",
    company: "Royal Mail",
    serviceName: "Tracked 48",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 3 },
    reliabilityScore: 8.7,
    tags: ["cheapest", "best_value"],
    baseRate: 3.50,
    perAdditionalHalfKgRate: 0.80,
    distanceRate: 0.20,
    maxWeightAllowed: 20
  },
  {
    id: "royal-mail-special-delivery",
    company: "Royal Mail",
    serviceName: "Special Delivery Guaranteed",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.7,
    tags: ["premium", "most_reliable"],
    baseRate: 9.50,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "dpd-local-gb",
    company: "DPD",
    serviceName: "Local Next Day",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.5,
    tags: ["fastest", "business_friendly"],
    baseRate: 7.20,
    perAdditionalHalfKgRate: 1.40,
    distanceRate: 0.35,
    maxWeightAllowed: 30
  },
  {
    id: "evri-standard-gb",
    company: "Evri",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 2.80,
    perAdditionalHalfKgRate: 0.60,
    distanceRate: 0.15,
    maxWeightAllowed: 15
  },
  {
    id: "parcelforce-express24",
    company: "Parcelforce",
    serviceName: "Express24",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.9,
    tags: ["reliable"],
    baseRate: 6.80,
    perAdditionalHalfKgRate: 1.30,
    distanceRate: 0.32,
    maxWeightAllowed: 30
  },
  {
    id: "ups-standard-gb",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["reliable", "business_friendly"],
    baseRate: 6.20,
    perAdditionalHalfKgRate: 1.20,
    distanceRate: 0.30,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-parcel-uk",
    company: "DHL",
    serviceName: "Parcel UK Next Day",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.1,
    tags: ["fastest"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.50,
    distanceRate: 0.50,
    maxWeightAllowed: 50
  },
  {
    id: "dhl-express-gb",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-gb",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-gb",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "parcelforce-worldwide",
    company: "Parcelforce",
    serviceName: "Global Priority",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 8.5,
    tags: ["best_value"],
    baseRate: 16.00,
    perAdditionalHalfKgRate: 5.50,
    distanceRate: 1.80,
    maxWeightAllowed: 30
  },
  {
    id: "royal-mail-intl-tracked",
    company: "Royal Mail",
    serviceName: "International Tracked",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 5, max: 9 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "student_friendly"],
    baseRate: 10.50,
    perAdditionalHalfKgRate: 3.50,
    distanceRate: 1.10,
    maxWeightAllowed: 20
  },

  // ================= CA COURIERS =================
  {
    id: "canadapost-regular",
    company: "Canada Post",
    serviceName: "Regular Parcel",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 3, max: 9 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "student_friendly"],
    baseRate: 9.80,
    perAdditionalHalfKgRate: 1.80,
    distanceRate: 0.45,
    maxWeightAllowed: 30
  },
  {
    id: "canadapost-expedited",
    company: "Canada Post",
    serviceName: "Expedited Parcel",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 7 },
    reliabilityScore: 8.5,
    tags: ["best_value", "ecommerce_friendly"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.20,
    distanceRate: 0.55,
    maxWeightAllowed: 30
  },
  {
    id: "canadapost-xpresspost",
    company: "Canada Post",
    serviceName: "Xpresspost",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.9,
    tags: ["fastest"],
    baseRate: 18.50,
    perAdditionalHalfKgRate: 3.20,
    distanceRate: 0.85,
    maxWeightAllowed: 30
  },
  {
    id: "purolator-express",
    company: "Purolator",
    serviceName: "Express",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.4,
    tags: ["fastest", "premium"],
    baseRate: 24.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.10,
    maxWeightAllowed: 65
  },
  {
    id: "ups-standard-ca",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.2,
    tags: ["reliable", "business_friendly"],
    baseRate: 14.90,
    perAdditionalHalfKgRate: 2.20,
    distanceRate: 0.65,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-ground-ca",
    company: "FedEx",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.1,
    tags: ["reliable"],
    baseRate: 16.50,
    perAdditionalHalfKgRate: 2.60,
    distanceRate: 0.75,
    maxWeightAllowed: 70
  },
  {
    id: "canpar-ground",
    company: "Canpar",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "ecommerce_friendly", "regional_specialist"],
    baseRate: 9.00,
    perAdditionalHalfKgRate: 1.65,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "dhl-express-ca",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-ca",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-ca",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "canadapost-intl",
    company: "Canada Post",
    serviceName: "International Parcel",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 14 },
    reliabilityScore: 7.8,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.00,
    perAdditionalHalfKgRate: 3.70,
    distanceRate: 1.20,
    maxWeightAllowed: 30
  },

  // ================= AU COURIERS =================
  {
    id: "auspost-parcel-post",
    company: "Australia Post",
    serviceName: "Parcel Post",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.7,
    tags: ["cheapest", "best_value"],
    baseRate: 8.95,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.50,
    maxWeightAllowed: 22
  },
  {
    id: "auspost-express-post",
    company: "Australia Post",
    serviceName: "Express Post",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.3,
    tags: ["fastest", "reliable"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.40,
    distanceRate: 0.70,
    maxWeightAllowed: 22
  },
  {
    id: "startrack-premium",
    company: "StarTrack",
    serviceName: "Premium Express",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.4,
    tags: ["fastest", "business_friendly"],
    baseRate: 21.50,
    perAdditionalHalfKgRate: 3.50,
    distanceRate: 0.95,
    maxWeightAllowed: 50
  },
  {
    id: "couriersplease-standard",
    company: "CouriersPlease",
    serviceName: "Standard Parcel",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 7.95,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 25
  },
  {
    id: "aramex-au-domestic",
    company: "Aramex",
    serviceName: "Domestic Courier",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 7.6,
    tags: ["cheapest"],
    baseRate: 8.50,
    perAdditionalHalfKgRate: 1.60,
    distanceRate: 0.45,
    maxWeightAllowed: 30
  },
  {
    id: "dhl-express-au",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-au",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-au",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.3,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "auspost-intl-parcel",
    company: "Australia Post",
    serviceName: "International Standard",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 12 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.20,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.25,
    maxWeightAllowed: 20
  },

  // ================= DE COURIERS =================
  {
    id: "dhl-paket-de",
    company: "DHL",
    serviceName: "Paket",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.4,
    tags: ["most_reliable", "best_value"],
    baseRate: 4.99,
    perAdditionalHalfKgRate: 0.70,
    distanceRate: 0.15,
    maxWeightAllowed: 31.5
  },
  {
    id: "hermes-de",
    company: "Hermes",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 8.1,
    tags: ["cheapest", "student_friendly"],
    baseRate: 3.99,
    perAdditionalHalfKgRate: 0.60,
    distanceRate: 0.10,
    maxWeightAllowed: 25
  },
  {
    id: "dpd-de",
    company: "DPD",
    serviceName: "Classic",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.8,
    tags: ["ecommerce_friendly"],
    baseRate: 5.40,
    perAdditionalHalfKgRate: 0.90,
    distanceRate: 0.20,
    maxWeightAllowed: 31.5
  },
  {
    id: "gls-de",
    company: "GLS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "business_friendly"],
    baseRate: 4.80,
    perAdditionalHalfKgRate: 0.85,
    distanceRate: 0.18,
    maxWeightAllowed: 40
  },
  {
    id: "ups-standard-de",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["fastest", "reliable"],
    baseRate: 8.50,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 50
  },
  {
    id: "dhl-express-de",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.7,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-de",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-de",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "gls-intl-de",
    company: "GLS",
    serviceName: "International",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 4, max: 8 },
    reliabilityScore: 8.3,
    tags: ["cheapest", "best_value"],
    baseRate: 12.00,
    perAdditionalHalfKgRate: 4.00,
    distanceRate: 1.30,
    maxWeightAllowed: 40
  },

  // ================= AE COURIERS =================
  {
    id: "emirates-post-domestic",
    company: "Emirates Post",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 2.00,
    distanceRate: 2.50,
    maxWeightAllowed: 35
  },
  {
    id: "aramex-domestic-ae",
    company: "Aramex",
    serviceName: "Domestic Express",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["reliable", "best_value"],
    baseRate: 19.00,
    perAdditionalHalfKgRate: 3.00,
    distanceRate: 4.00,
    maxWeightAllowed: 30
  },
  {
    id: "shipa-delivery-ae",
    company: "Shipa Delivery",
    serviceName: "Next Day Delivery",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.4,
    tags: ["fastest", "ecommerce_friendly"],
    baseRate: 24.00,
    perAdditionalHalfKgRate: 4.00,
    distanceRate: 5.00,
    maxWeightAllowed: 20
  },
  {
    id: "aramex-intl-ae",
    company: "Aramex",
    serviceName: "International Express",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 6 },
    reliabilityScore: 9.0,
    tags: ["best_value", "regional_specialist"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 5.00,
    distanceRate: 1.60,
    maxWeightAllowed: 100
  },
  {
    id: "dhl-express-ae",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-ae",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-ae",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.2,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },

  // ================= IN COURIERS =================
  {
    id: "indiapost-domestic-in",
    company: "India Post",
    serviceName: "Speed Post",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "student_friendly"],
    baseRate: 40.00,
    perAdditionalHalfKgRate: 15.00,
    distanceRate: 8.00,
    maxWeightAllowed: 35
  },
  {
    id: "bluedart-domestic-in",
    company: "Blue Dart",
    serviceName: "Domestic Priority",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.6,
    tags: ["fastest", "premium", "business_friendly"],
    baseRate: 160.00,
    perAdditionalHalfKgRate: 45.00,
    distanceRate: 25.00,
    maxWeightAllowed: 100
  },
  {
    id: "dtdc-domestic-in",
    company: "DTDC",
    serviceName: "Lite / Plus",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.8,
    tags: ["best_value", "reliable"],
    baseRate: 80.00,
    perAdditionalHalfKgRate: 25.00,
    distanceRate: 15.00,
    maxWeightAllowed: 70
  },
  {
    id: "delhivery-domestic-in",
    company: "Delhivery",
    serviceName: "Express",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.9,
    tags: ["ecommerce_friendly"],
    baseRate: 70.00,
    perAdditionalHalfKgRate: 22.00,
    distanceRate: 12.00,
    maxWeightAllowed: 150
  },
  {
    id: "xpressbees-domestic-in",
    company: "XpressBees",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.4,
    tags: ["ecommerce_friendly", "cheapest"],
    baseRate: 50.00,
    perAdditionalHalfKgRate: 18.00,
    distanceRate: 10.00,
    maxWeightAllowed: 50
  },
  {
    id: "ecomexpress-domestic-in",
    company: "Ecom Express",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.5,
    tags: ["ecommerce_friendly"],
    baseRate: 55.00,
    perAdditionalHalfKgRate: 19.00,
    distanceRate: 11.00,
    maxWeightAllowed: 50
  },
  {
    id: "shadowfax-domestic-in",
    company: "Shadowfax",
    serviceName: "Express",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 4 },
    reliabilityScore: 8.6,
    tags: ["fastest", "ecommerce_friendly"],
    baseRate: 65.00,
    perAdditionalHalfKgRate: 20.00,
    distanceRate: 12.00,
    maxWeightAllowed: 40
  },
  {
    id: "porter-domestic-in",
    company: "Porter",
    serviceName: "City Courier",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.0,
    tags: ["fastest", "regional_specialist"],
    baseRate: 250.00,
    perAdditionalHalfKgRate: 35.00,
    distanceRate: 150.00,
    maxWeightAllowed: 2000
  },
  {
    id: "professional-domestic-in",
    company: "Professional Couriers",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.2,
    tags: ["best_value"],
    baseRate: 45.00,
    perAdditionalHalfKgRate: 14.00,
    distanceRate: 9.00,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-express-in",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-in",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 5 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-in",
    company: "UPS",
    serviceName: "Worldwide Express",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 6 },
    reliabilityScore: 9.3,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "aramex-intl-in",
    company: "Aramex",
    serviceName: "International Parcel",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 4, max: 7 },
    reliabilityScore: 8.8,
    tags: ["best_value"],
    baseRate: 14.50,
    perAdditionalHalfKgRate: 4.80,
    distanceRate: 1.60,
    maxWeightAllowed: 100
  },
  {
    id: "garudavega-intl-in",
    company: "Garudavega",
    serviceName: "International",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 5, max: 9 },
    reliabilityScore: 8.7,
    tags: ["regional_specialist", "best_value"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 4.20,
    distanceRate: 1.40,
    maxWeightAllowed: 150
  },
  {
    id: "indiapost-ems-in",
    company: "India Post",
    serviceName: "EMS Speed Post",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 7, max: 14 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 9.50,
    perAdditionalHalfKgRate: 3.20,
    distanceRate: 1.10,
    maxWeightAllowed: 35
  }
];

export interface PricingRule {
  baseRate: number;
  baseWeightLimit: number;
  perUnitWeightCost: number;
  pickupSurcharge?: number;
  expressMultiplier?: number;
}

export const DOMESTIC_PRICING_RULES: Record<string, Record<string, PricingRule>> = {
  "US": {
    "usps-ground-advantage": {
      "baseRate": 4.75,
      "baseWeightLimit": 1,
      "perUnitWeightCost": 0.65,
      "pickupSurcharge": 0.00,
      "expressMultiplier": 1.0
    },
    "fedex-ground-us": {
      "baseRate": 8.50,
      "baseWeightLimit": 1,
      "perUnitWeightCost": 1.25,
      "pickupSurcharge": 4.00,
      "expressMultiplier": 1.0
    },
    "ups-ground-us": {
      "baseRate": 8.75,
      "baseWeightLimit": 1,
      "perUnitWeightCost": 1.30,
      "pickupSurcharge": 4.00,
      "expressMultiplier": 1.0
    },
    "ontrac-regional-us": {
      "baseRate": 7.10,
      "baseWeightLimit": 1,
      "perUnitWeightCost": 0.95,
      "pickupSurcharge": 3.50,
      "expressMultiplier": 1.0
    },
    "lso-regional-tx": {
      "baseRate": 7.50,
      "baseWeightLimit": 1,
      "perUnitWeightCost": 1.10,
      "pickupSurcharge": 3.00,
      "expressMultiplier": 1.5
    }
  },
  "GB": {
    "royal-mail-tracked-24": { "baseRate": 4.15, "baseWeightLimit": 1, "perUnitWeightCost": 1.20, "pickupSurcharge": 0.50 },
    "royal-mail-tracked-48": { "baseRate": 3.40, "baseWeightLimit": 1, "perUnitWeightCost": 1.00, "pickupSurcharge": 0.50 },
    "royal-mail-special-delivery": { "baseRate": 7.35, "baseWeightLimit": 1, "perUnitWeightCost": 2.50, "pickupSurcharge": 0.00 },
    "evri-standard-gb": { "baseRate": 2.99, "baseWeightLimit": 1, "perUnitWeightCost": 0.85, "pickupSurcharge": 0.00 },
    "dpd-local-gb": { "baseRate": 6.50, "baseWeightLimit": 1, "perUnitWeightCost": 1.40, "pickupSurcharge": 2.00 },
    "parcelforce-express24": { "baseRate": 8.10, "baseWeightLimit": 1, "perUnitWeightCost": 1.30, "pickupSurcharge": 2.50 },
    "ups-standard-gb": { "baseRate": 7.90, "baseWeightLimit": 1, "perUnitWeightCost": 1.50, "pickupSurcharge": 2.00 },
    "dhl-parcel-uk": { "baseRate": 7.50, "baseWeightLimit": 1, "perUnitWeightCost": 1.60, "pickupSurcharge": 2.00 }
  },
  "CA": {
    "canadapost-regular": { "baseRate": 16.50, "baseWeightLimit": 1, "perUnitWeightCost": 2.50, "pickupSurcharge": 0.00 },
    "canpar-ground": { "baseRate": 14.75, "baseWeightLimit": 1, "perUnitWeightCost": 2.25, "pickupSurcharge": 3.00 },
    "canadapost-expedited": { "baseRate": 18.50, "baseWeightLimit": 1, "perUnitWeightCost": 2.75, "pickupSurcharge": 3.50 },
    "fedex-ground-ca": { "baseRate": 21.00, "baseWeightLimit": 1, "perUnitWeightCost": 3.25, "pickupSurcharge": 4.00 },
    "ups-standard-ca": { "baseRate": 21.50, "baseWeightLimit": 1, "perUnitWeightCost": 3.30, "pickupSurcharge": 4.00 },
    "canadapost-xpresspost": { "baseRate": 26.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.50, "pickupSurcharge": 3.50 },
    "purolator-express": { "baseRate": 32.00, "baseWeightLimit": 1, "perUnitWeightCost": 5.00, "pickupSurcharge": 5.00 }
  },
  "AU": {
    "aramex-au-domestic": { "baseRate": 9.95, "baseWeightLimit": 1, "perUnitWeightCost": 1.80, "pickupSurcharge": 0.00 },
    "auspost-parcel-post": { "baseRate": 10.95, "baseWeightLimit": 1, "perUnitWeightCost": 2.20, "pickupSurcharge": 0.00 },
    "couriersplease-standard": { "baseRate": 11.50, "baseWeightLimit": 1, "perUnitWeightCost": 2.00, "pickupSurcharge": 2.50 },
    "auspost-express-post": { "baseRate": 14.95, "baseWeightLimit": 1, "perUnitWeightCost": 3.50, "pickupSurcharge": 0.00 },
    "startrack-premium": { "baseRate": 18.50, "baseWeightLimit": 1, "perUnitWeightCost": 3.80, "pickupSurcharge": 4.50 }
  },
  "DE": {
    "hermes-de": { "baseRate": 4.50, "baseWeightLimit": 1, "perUnitWeightCost": 0.70, "pickupSurcharge": 2.50 },
    "gls-de": { "baseRate": 4.30, "baseWeightLimit": 1, "perUnitWeightCost": 0.75, "pickupSurcharge": 0.00 },
    "dpd-de": { "baseRate": 4.90, "baseWeightLimit": 1, "perUnitWeightCost": 0.80, "pickupSurcharge": 2.50 },
    "dhl-paket-de": { "baseRate": 5.49, "baseWeightLimit": 1, "perUnitWeightCost": 0.90, "pickupSurcharge": 3.00 },
    "ups-standard-de": { "baseRate": 7.50, "baseWeightLimit": 1, "perUnitWeightCost": 1.20, "pickupSurcharge": 4.00 }
  },
  "AE": {
    "emirates-post-domestic": { "baseRate": 25.00, "baseWeightLimit": 1, "perUnitWeightCost": 5.00, "pickupSurcharge": 0.00 },
    "aramex-domestic-ae": { "baseRate": 30.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.50, "pickupSurcharge": 10.00 },
    "shipa-delivery-ae": { "baseRate": 35.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.50, "pickupSurcharge": 0.00 }
  },
  "IN": {
    "indiapost-domestic-in": { "baseRate": 42.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 40.00, "pickupSurcharge": 0.00 },
    "xpressbees-domestic-in": { "baseRate": 55.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 50.00, "pickupSurcharge": 10.00 },
    "ecomexpress-domestic-in": { "baseRate": 60.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 55.00, "pickupSurcharge": 10.00 },
    "delhivery-domestic-in": { "baseRate": 65.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 60.00, "pickupSurcharge": 0.00 },
    "shadowfax-domestic-in": { "baseRate": 65.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 60.00, "pickupSurcharge": 10.00 },
    "professional-domestic-in": { "baseRate": 70.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 65.00, "pickupSurcharge": 15.00 },
    "dtdc-domestic-in": { "baseRate": 85.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 75.00, "pickupSurcharge": 25.00 },
    "porter-domestic-in": { "baseRate": 150.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 20.00, "pickupSurcharge": 0.00 },
    "bluedart-domestic-in": { "baseRate": 180.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 120.00, "pickupSurcharge": 50.00 }
  }
};

export const INTERNATIONAL_PRICING_RULES: Record<string, Record<string, PricingRule>> = {
  "US_TO_CA": {
    "usps-priority-intl": { "baseRate": 30.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.50 },
    "fedex-intl-economy": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.50 },
    "dhl-express-worldwide-us": { "baseRate": 55.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.00 }
  },
  "US_TO_GB": {
    "usps-priority-intl": { "baseRate": 42.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.00 },
    "fedex-intl-economy": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.50 },
    "dhl-express-worldwide-us": { "baseRate": 75.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 }
  },
  "US_TO_AU": {
    "usps-priority-intl": { "baseRate": 48.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 },
    "fedex-intl-economy": { "baseRate": 85.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "dhl-express-worldwide-us": { "baseRate": 95.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.00 }
  },
  "US_TO_IN": {
    "usps-priority-intl": { "baseRate": 52.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.00 },
    "fedex-intl-economy": { "baseRate": 90.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 },
    "dhl-express-worldwide-us": { "baseRate": 105.00, "baseWeightLimit": 1, "perUnitWeightCost": 16.00 }
  },
  "US_TO_DE": {
    "usps-priority-intl": { "baseRate": 42.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.00 },
    "fedex-intl-economy": { "baseRate": 68.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.50 },
    "dhl-express-worldwide-us": { "baseRate": 78.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 }
  },
  "US_TO_AE": {
    "usps-priority-intl": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.50 },
    "fedex-intl-economy": { "baseRate": 75.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 },
    "dhl-express-worldwide-us": { "baseRate": 85.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 }
  },
  "GB_TO_US": {
    "royal-mail-intl-tracked": { "baseRate": 16.50, "baseWeightLimit": 1, "perUnitWeightCost": 5.50 },
    "parcelforce-worldwide": { "baseRate": 38.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.00 },
    "dhl-express-gb": { "baseRate": 48.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.50 },
    "ups-worldwide-gb": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.00 },
    "fedex-intl-gb": { "baseRate": 42.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 }
  },
  "GB_TO_DE": {
    "royal-mail-intl-tracked": { "baseRate": 10.50, "baseWeightLimit": 1, "perUnitWeightCost": 3.50 },
    "parcelforce-worldwide": { "baseRate": 25.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.50 },
    "dhl-express-gb": { "baseRate": 32.00, "baseWeightLimit": 1, "perUnitWeightCost": 5.50 },
    "ups-worldwide-gb": { "baseRate": 28.00, "baseWeightLimit": 1, "perUnitWeightCost": 5.00 },
    "fedex-intl-gb": { "baseRate": 29.00, "baseWeightLimit": 1, "perUnitWeightCost": 5.20 }
  },
  "GB_TO_AU": {
    "royal-mail-intl-tracked": { "baseRate": 19.50, "baseWeightLimit": 1, "perUnitWeightCost": 7.50 },
    "parcelforce-worldwide": { "baseRate": 55.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 },
    "dhl-express-gb": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 },
    "ups-worldwide-gb": { "baseRate": 62.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 },
    "fedex-intl-gb": { "baseRate": 60.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.50 }
  },
  "GB_TO_IN": {
    "royal-mail-intl-tracked": { "baseRate": 18.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.00 },
    "parcelforce-worldwide": { "baseRate": 52.00, "baseWeightLimit": 1, "perUnitWeightCost": 10.50 },
    "dhl-express-gb": { "baseRate": 60.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.50 },
    "ups-worldwide-gb": { "baseRate": 58.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "fedex-intl-gb": { "baseRate": 55.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.50 }
  },
  "CA_TO_US": {
    "canadapost-intl": { "baseRate": 22.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.50 },
    "fedex-intl-ca": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.50 },
    "ups-worldwide-ca": { "baseRate": 48.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.00 },
    "dhl-express-ca": { "baseRate": 55.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.00 }
  },
  "CA_TO_GB": {
    "canadapost-intl": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.50 },
    "fedex-intl-ca": { "baseRate": 85.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.50 },
    "ups-worldwide-ca": { "baseRate": 88.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 },
    "dhl-express-ca": { "baseRate": 95.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 }
  },
  "CA_TO_DE": {
    "canadapost-intl": { "baseRate": 48.00, "baseWeightLimit": 1, "perUnitWeightCost": 10.00 },
    "fedex-intl-ca": { "baseRate": 88.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 },
    "ups-worldwide-ca": { "baseRate": 92.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.50 },
    "dhl-express-ca": { "baseRate": 98.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.00 }
  },
  "CA_TO_AU": {
    "canadapost-intl": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.00 },
    "fedex-intl-ca": { "baseRate": 125.00, "baseWeightLimit": 1, "perUnitWeightCost": 18.50 },
    "ups-worldwide-ca": { "baseRate": 130.00, "baseWeightLimit": 1, "perUnitWeightCost": 19.00 },
    "dhl-express-ca": { "baseRate": 145.00, "baseWeightLimit": 1, "perUnitWeightCost": 22.00 }
  },
  "CA_TO_AE": {
    "canadapost-intl": { "baseRate": 70.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.00 },
    "fedex-intl-ca": { "baseRate": 135.00, "baseWeightLimit": 1, "perUnitWeightCost": 20.00 },
    "ups-worldwide-ca": { "baseRate": 140.00, "baseWeightLimit": 1, "perUnitWeightCost": 21.00 },
    "dhl-express-ca": { "baseRate": 155.00, "baseWeightLimit": 1, "perUnitWeightCost": 23.50 }
  },
  "CA_TO_IN": {
    "canadapost-intl": { "baseRate": 75.00, "baseWeightLimit": 1, "perUnitWeightCost": 16.00 },
    "fedex-intl-ca": { "baseRate": 145.00, "baseWeightLimit": 1, "perUnitWeightCost": 22.00 },
    "ups-worldwide-ca": { "baseRate": 150.00, "baseWeightLimit": 1, "perUnitWeightCost": 23.00 },
    "dhl-express-ca": { "baseRate": 165.00, "baseWeightLimit": 1, "perUnitWeightCost": 25.00 }
  },
  "AU_TO_US": {
    "auspost-intl-parcel": { "baseRate": 28.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.50 },
    "ups-worldwide-au": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "fedex-intl-au": { "baseRate": 68.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.50 },
    "dhl-express-au": { "baseRate": 75.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.00 }
  },
  "AU_TO_CA": {
    "auspost-intl-parcel": { "baseRate": 32.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.00 },
    "ups-worldwide-au": { "baseRate": 70.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 },
    "fedex-intl-au": { "baseRate": 72.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.50 },
    "dhl-express-au": { "baseRate": 79.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.00 }
  },
  "AU_TO_GB": {
    "auspost-intl-parcel": { "baseRate": 34.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 },
    "ups-worldwide-au": { "baseRate": 74.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.00 },
    "fedex-intl-au": { "baseRate": 76.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 },
    "dhl-express-au": { "baseRate": 85.00, "baseWeightLimit": 1, "perUnitWeightCost": 16.00 }
  },
  "AU_TO_DE": {
    "auspost-intl-parcel": { "baseRate": 36.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.00 },
    "ups-worldwide-au": { "baseRate": 76.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 },
    "fedex-intl-au": { "baseRate": 78.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.00 },
    "dhl-express-au": { "baseRate": 88.00, "baseWeightLimit": 1, "perUnitWeightCost": 16.50 }
  },
  "AU_TO_IN": {
    "auspost-intl-parcel": { "baseRate": 26.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.80 },
    "ups-worldwide-au": { "baseRate": 58.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 },
    "fedex-intl-au": { "baseRate": 60.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.50 },
    "dhl-express-au": { "baseRate": 68.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 }
  },
  "AU_TO_AE": {
    "auspost-intl-parcel": { "baseRate": 30.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.20 },
    "ups-worldwide-au": { "baseRate": 62.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.50 },
    "fedex-intl-au": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "dhl-express-au": { "baseRate": 72.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.50 }
  },
  "DE_TO_GB": {
    "gls-intl-de": { "baseRate": 14.50, "baseWeightLimit": 1, "perUnitWeightCost": 2.50 },
    "dhl-express-de": { "baseRate": 28.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.50 },
    "ups-worldwide-de": { "baseRate": 26.00, "baseWeightLimit": 1, "perUnitWeightCost": 4.00 },
    "fedex-intl-de": { "baseRate": 27.50, "baseWeightLimit": 1, "perUnitWeightCost": 4.20 }
  },
  "DE_TO_US": {
    "gls-intl-de": { "baseRate": 24.00, "baseWeightLimit": 1, "perUnitWeightCost": 6.50 },
    "dhl-express-de": { "baseRate": 42.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.00 },
    "ups-worldwide-de": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 },
    "fedex-intl-de": { "baseRate": 44.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.20 }
  },
  "DE_TO_CA": {
    "gls-intl-de": { "baseRate": 26.00, "baseWeightLimit": 1, "perUnitWeightCost": 7.00 },
    "dhl-express-de": { "baseRate": 45.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 },
    "ups-worldwide-de": { "baseRate": 48.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.00 },
    "fedex-intl-de": { "baseRate": 47.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.80 }
  },
  "DE_TO_AE": {
    "gls-intl-de": { "baseRate": 32.00, "baseWeightLimit": 1, "perUnitWeightCost": 8.50 },
    "dhl-express-de": { "baseRate": 55.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.50 },
    "ups-worldwide-de": { "baseRate": 58.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "fedex-intl-de": { "baseRate": 60.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.50 }
  },
  "DE_TO_IN": {
    "gls-intl-de": { "baseRate": 34.00, "baseWeightLimit": 1, "perUnitWeightCost": 9.00 },
    "dhl-express-de": { "baseRate": 58.00, "baseWeightLimit": 1, "perUnitWeightCost": 12.00 },
    "ups-worldwide-de": { "baseRate": 62.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.00 },
    "fedex-intl-de": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 13.50 }
  },
  "DE_TO_AU": {
    "gls-intl-de": { "baseRate": 38.00, "baseWeightLimit": 1, "perUnitWeightCost": 11.00 },
    "dhl-express-de": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 14.50 },
    "ups-worldwide-de": { "baseRate": 70.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.50 },
    "fedex-intl-de": { "baseRate": 72.00, "baseWeightLimit": 1, "perUnitWeightCost": 16.00 }
  },
  "AE_TO_IN": {
    "aramex-intl-ae": { "baseRate": 65.00, "baseWeightLimit": 1, "perUnitWeightCost": 15.00 },
    "fedex-intl-ae": { "baseRate": 110.00, "baseWeightLimit": 1, "perUnitWeightCost": 25.00 },
    "ups-worldwide-ae": { "baseRate": 125.00, "baseWeightLimit": 1, "perUnitWeightCost": 28.00 },
    "dhl-express-ae": { "baseRate": 140.00, "baseWeightLimit": 1, "perUnitWeightCost": 32.00 }
  },
  "AE_TO_GB": {
    "aramex-intl-ae": { "baseRate": 110.00, "baseWeightLimit": 1, "perUnitWeightCost": 25.00 },
    "fedex-intl-ae": { "baseRate": 165.00, "baseWeightLimit": 1, "perUnitWeightCost": 38.00 },
    "ups-worldwide-ae": { "baseRate": 175.00, "baseWeightLimit": 1, "perUnitWeightCost": 40.00 },
    "dhl-express-ae": { "baseRate": 195.00, "baseWeightLimit": 1, "perUnitWeightCost": 45.00 }
  },
  "AE_TO_DE": {
    "aramex-intl-ae": { "baseRate": 115.00, "baseWeightLimit": 1, "perUnitWeightCost": 26.00 },
    "fedex-intl-ae": { "baseRate": 170.00, "baseWeightLimit": 1, "perUnitWeightCost": 39.00 },
    "ups-worldwide-ae": { "baseRate": 180.00, "baseWeightLimit": 1, "perUnitWeightCost": 42.00 },
    "dhl-express-ae": { "baseRate": 205.00, "baseWeightLimit": 1, "perUnitWeightCost": 47.00 }
  },
  "AE_TO_US": {
    "aramex-intl-ae": { "baseRate": 145.00, "baseWeightLimit": 1, "perUnitWeightCost": 35.00 },
    "fedex-intl-ae": { "baseRate": 240.00, "baseWeightLimit": 1, "perUnitWeightCost": 55.00 },
    "ups-worldwide-ae": { "baseRate": 255.00, "baseWeightLimit": 1, "perUnitWeightCost": 58.00 },
    "dhl-express-ae": { "baseRate": 285.00, "baseWeightLimit": 1, "perUnitWeightCost": 65.00 }
  },
  "AE_TO_CA": {
    "aramex-intl-ae": { "baseRate": 155.00, "baseWeightLimit": 1, "perUnitWeightCost": 38.00 },
    "fedex-intl-ae": { "baseRate": 250.00, "baseWeightLimit": 1, "perUnitWeightCost": 58.00 },
    "ups-worldwide-ae": { "baseRate": 265.00, "baseWeightLimit": 1, "perUnitWeightCost": 62.00 },
    "dhl-express-ae": { "baseRate": 295.00, "baseWeightLimit": 1, "perUnitWeightCost": 68.00 }
  },
  "AE_TO_AU": {
    "aramex-intl-ae": { "baseRate": 165.00, "baseWeightLimit": 1, "perUnitWeightCost": 42.00 },
    "fedex-intl-ae": { "baseRate": 270.00, "baseWeightLimit": 1, "perUnitWeightCost": 65.00 },
    "ups-worldwide-ae": { "baseRate": 285.00, "baseWeightLimit": 1, "perUnitWeightCost": 68.00 },
    "dhl-express-ae": { "baseRate": 315.00, "baseWeightLimit": 1, "perUnitWeightCost": 75.00 }
  },
  "IN_TO_AE": {
    "indiapost-ems-in": { "baseRate": 850.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 500.00 },
    "garudavega-intl-in": { "baseRate": 1050.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 600.00 },
    "aramex-intl-in": { "baseRate": 1200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 650.00 },
    "fedex-intl-in": { "baseRate": 2400.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 900.00 },
    "ups-worldwide-in": { "baseRate": 2500.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 950.00 },
    "dhl-express-in": { "baseRate": 2600.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1000.00 }
  },
  "IN_TO_GB": {
    "indiapost-ems-in": { "baseRate": 1150.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 700.00 },
    "garudavega-intl-in": { "baseRate": 1300.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 800.00 },
    "aramex-intl-in": { "baseRate": 1800.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 900.00 },
    "fedex-intl-in": { "baseRate": 3100.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1300.00 },
    "ups-worldwide-in": { "baseRate": 3200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1350.00 },
    "dhl-express-in": { "baseRate": 3350.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1400.00 }
  },
  "IN_TO_DE": {
    "indiapost-ems-in": { "baseRate": 1200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 750.00 },
    "garudavega-intl-in": { "baseRate": 1350.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 850.00 },
    "aramex-intl-in": { "baseRate": 1900.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 950.00 },
    "fedex-intl-in": { "baseRate": 3200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1350.00 },
    "ups-worldwide-in": { "baseRate": 3300.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1400.00 },
    "dhl-express-in": { "baseRate": 3500.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1450.00 }
  },
  "IN_TO_US": {
    "indiapost-ems-in": { "baseRate": 1450.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 850.00 },
    "garudavega-intl-in": { "baseRate": 1650.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 950.00 },
    "aramex-intl-in": { "baseRate": 2200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1100.00 },
    "fedex-intl-in": { "baseRate": 3600.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1600.00 },
    "ups-worldwide-in": { "baseRate": 3750.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1650.00 },
    "dhl-express-in": { "baseRate": 3900.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1700.00 }
  },
  "IN_TO_CA": {
    "indiapost-ems-in": { "baseRate": 1500.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 900.00 },
    "garudavega-intl-in": { "baseRate": 1700.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1000.00 },
    "aramex-intl-in": { "baseRate": 2400.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1200.00 },
    "fedex-intl-in": { "baseRate": 3900.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1800.00 },
    "ups-worldwide-in": { "baseRate": 4100.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1850.00 },
    "dhl-express-in": { "baseRate": 4250.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1900.00 }
  },
  "IN_TO_AU": {
    "indiapost-ems-in": { "baseRate": 1400.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 900.00 },
    "garudavega-intl-in": { "baseRate": 1600.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1000.00 },
    "aramex-intl-in": { "baseRate": 2600.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1300.00 },
    "fedex-intl-in": { "baseRate": 4100.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1850.00 },
    "ups-worldwide-in": { "baseRate": 4200.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 1900.00 },
    "dhl-express-in": { "baseRate": 4500.00, "baseWeightLimit": 0.5, "perUnitWeightCost": 2000.00 }
  }
};
