// src/utils/courierData.ts

export interface CourierService {
  id: string;
  company: string;
  serviceName: string;
  type: "domestic" | "international";
  originCountry: string;
  supportedRoutes: string[];
  features: {
    tracking: boolean;
    insurance: boolean;
    pickup: boolean;
  };
  deliveryDays: {
    min: number;
    max: number;
  };
  reliabilityScore: number;
  tags: string[];

  // Pricing coefficients for mockup calculation
  baseRate: number;                  // local currency (domestic) or USD (international)
  perAdditionalHalfKgRate: number;   // local currency (domestic) or USD (international)
  distanceRate: number;              // local currency (domestic) or USD (international)
  maxWeightAllowed: number;          // in kg
}

export const COURIER_SERVICES: CourierService[] = [
  // ================= US COURIERS =================
  {
    id: "ups-ground-us",
    company: "UPS",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.3,
    tags: ["most_reliable", "business_friendly"],
    baseRate: 13.80,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.55,
    maxWeightAllowed: 70
  },
  {
    id: "ups-3-day-select",
    company: "UPS",
    serviceName: "3 Day Select",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.4,
    tags: ["reliable"],
    baseRate: 22.50,
    perAdditionalHalfKgRate: 2.80,
    distanceRate: 0.75,
    maxWeightAllowed: 70
  },
  {
    id: "ups-next-day-air",
    company: "UPS",
    serviceName: "Next Day Air",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.8,
    tags: ["fastest", "premium"],
    baseRate: 38.00,
    perAdditionalHalfKgRate: 4.80,
    distanceRate: 1.20,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-ground-us",
    company: "FedEx",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.2,
    tags: ["best_value", "business_friendly"],
    baseRate: 14.50,
    perAdditionalHalfKgRate: 2.10,
    distanceRate: 0.60,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-home-delivery",
    company: "FedEx",
    serviceName: "Home Delivery",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.1,
    tags: ["ecommerce_friendly"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 2.15,
    distanceRate: 0.65,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-express-saver",
    company: "FedEx",
    serviceName: "Express Saver",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 3 },
    reliabilityScore: 9.3,
    tags: ["reliable"],
    baseRate: 24.00,
    perAdditionalHalfKgRate: 3.10,
    distanceRate: 0.85,
    maxWeightAllowed: 70
  },
  {
    id: "usps-ground-advantage",
    company: "USPS",
    serviceName: "Ground Advantage",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 6.20,
    perAdditionalHalfKgRate: 1.10,
    distanceRate: 0.30,
    maxWeightAllowed: 30
  },
  {
    id: "usps-priority-mail",
    company: "USPS",
    serviceName: "Priority Mail",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 8.8,
    tags: ["best_value"],
    baseRate: 9.20,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "usps-priority-mail-express",
    company: "USPS",
    serviceName: "Priority Mail Express",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.0,
    tags: ["fastest"],
    baseRate: 28.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.00,
    maxWeightAllowed: 30
  },
  {
    id: "ontrac-regional-us",
    company: "OnTrac",
    serviceName: "Regional Ground",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.2,
    tags: ["fastest", "ecommerce_friendly", "regional_specialist"],
    baseRate: 11.50,
    perAdditionalHalfKgRate: 1.60,
    distanceRate: 0.50,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-ecommerce-us",
    company: "DHL",
    serviceName: "eCommerce",
    type: "domestic",
    originCountry: "US",
    supportedRoutes: ["US"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 3, max: 8 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 5.80,
    perAdditionalHalfKgRate: 1.00,
    distanceRate: 0.28,
    maxWeightAllowed: 25
  },
  {
    id: "dhl-express-worldwide",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-saver",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["fastest", "business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-expedited",
    company: "UPS",
    serviceName: "Worldwide Expedited",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.3,
    tags: ["reliable"],
    baseRate: 18.00,
    perAdditionalHalfKgRate: 6.20,
    distanceRate: 2.00,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-priority",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["fastest", "premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-economy",
    company: "FedEx",
    serviceName: "International Economy",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 4, max: 6 },
    reliabilityScore: 9.0,
    tags: ["best_value"],
    baseRate: 16.50,
    perAdditionalHalfKgRate: 5.80,
    distanceRate: 1.80,
    maxWeightAllowed: 300
  },
  {
    id: "usps-priority-intl",
    company: "USPS",
    serviceName: "Priority Mail International",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 10 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.20,
    maxWeightAllowed: 30
  },
  {
    id: "usps-express-mail-intl",
    company: "USPS",
    serviceName: "Express Mail International",
    type: "international",
    originCountry: "US",
    supportedRoutes: ["CA", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 3, max: 5 },
    reliabilityScore: 8.2,
    tags: ["best_value"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 5.00,
    distanceRate: 1.60,
    maxWeightAllowed: 30
  },

  // ================= GB COURIERS =================
  {
    id: "royal-mail-tracked-24",
    company: "Royal Mail",
    serviceName: "Tracked 24",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.8,
    tags: ["fastest", "student_friendly"],
    baseRate: 4.80,
    perAdditionalHalfKgRate: 1.10,
    distanceRate: 0.25,
    maxWeightAllowed: 20
  },
  {
    id: "royal-mail-tracked-48",
    company: "Royal Mail",
    serviceName: "Tracked 48",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 3 },
    reliabilityScore: 8.7,
    tags: ["cheapest", "best_value"],
    baseRate: 3.50,
    perAdditionalHalfKgRate: 0.80,
    distanceRate: 0.20,
    maxWeightAllowed: 20
  },
  {
    id: "royal-mail-special-delivery",
    company: "Royal Mail",
    serviceName: "Special Delivery Guaranteed",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.7,
    tags: ["premium", "most_reliable"],
    baseRate: 9.50,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "dpd-local-gb",
    company: "DPD",
    serviceName: "Local Next Day",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.5,
    tags: ["fastest", "business_friendly"],
    baseRate: 7.20,
    perAdditionalHalfKgRate: 1.40,
    distanceRate: 0.35,
    maxWeightAllowed: 30
  },
  {
    id: "evri-standard-gb",
    company: "Evri",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 2.80,
    perAdditionalHalfKgRate: 0.60,
    distanceRate: 0.15,
    maxWeightAllowed: 15
  },
  {
    id: "parcelforce-express24",
    company: "Parcelforce",
    serviceName: "Express24",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.9,
    tags: ["reliable"],
    baseRate: 6.80,
    perAdditionalHalfKgRate: 1.30,
    distanceRate: 0.32,
    maxWeightAllowed: 30
  },
  {
    id: "ups-standard-gb",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["reliable", "business_friendly"],
    baseRate: 6.20,
    perAdditionalHalfKgRate: 1.20,
    distanceRate: 0.30,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-parcel-uk",
    company: "DHL",
    serviceName: "Parcel UK Next Day",
    type: "domestic",
    originCountry: "GB",
    supportedRoutes: ["GB"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.1,
    tags: ["fastest"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.50,
    distanceRate: 0.50,
    maxWeightAllowed: 50
  },
  {
    id: "dhl-express-gb",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-gb",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-gb",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "parcelforce-worldwide",
    company: "Parcelforce",
    serviceName: "Global Priority",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 8.5,
    tags: ["best_value"],
    baseRate: 16.00,
    perAdditionalHalfKgRate: 5.50,
    distanceRate: 1.80,
    maxWeightAllowed: 30
  },
  {
    id: "royal-mail-intl-tracked",
    company: "Royal Mail",
    serviceName: "International Tracked",
    type: "international",
    originCountry: "GB",
    supportedRoutes: ["US", "CA", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 5, max: 9 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "student_friendly"],
    baseRate: 10.50,
    perAdditionalHalfKgRate: 3.50,
    distanceRate: 1.10,
    maxWeightAllowed: 20
  },

  // ================= CA COURIERS =================
  {
    id: "canadapost-regular",
    company: "Canada Post",
    serviceName: "Regular Parcel",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 3, max: 9 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "student_friendly"],
    baseRate: 9.80,
    perAdditionalHalfKgRate: 1.80,
    distanceRate: 0.45,
    maxWeightAllowed: 30
  },
  {
    id: "canadapost-expedited",
    company: "Canada Post",
    serviceName: "Expedited Parcel",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 7 },
    reliabilityScore: 8.5,
    tags: ["best_value", "ecommerce_friendly"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.20,
    distanceRate: 0.55,
    maxWeightAllowed: 30
  },
  {
    id: "canadapost-xpresspost",
    company: "Canada Post",
    serviceName: "Xpresspost",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.9,
    tags: ["fastest"],
    baseRate: 18.50,
    perAdditionalHalfKgRate: 3.20,
    distanceRate: 0.85,
    maxWeightAllowed: 30
  },
  {
    id: "purolator-express",
    company: "Purolator",
    serviceName: "Express",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.4,
    tags: ["fastest", "premium"],
    baseRate: 24.50,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.10,
    maxWeightAllowed: 65
  },
  {
    id: "ups-standard-ca",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.2,
    tags: ["reliable", "business_friendly"],
    baseRate: 14.90,
    perAdditionalHalfKgRate: 2.20,
    distanceRate: 0.65,
    maxWeightAllowed: 70
  },
  {
    id: "fedex-ground-ca",
    company: "FedEx",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 5 },
    reliabilityScore: 9.1,
    tags: ["reliable"],
    baseRate: 16.50,
    perAdditionalHalfKgRate: 2.60,
    distanceRate: 0.75,
    maxWeightAllowed: 70
  },
  {
    id: "canpar-ground",
    company: "Canpar",
    serviceName: "Ground",
    type: "domestic",
    originCountry: "CA",
    supportedRoutes: ["CA"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "ecommerce_friendly", "regional_specialist"],
    baseRate: 9.00,
    perAdditionalHalfKgRate: 1.65,
    distanceRate: 0.40,
    maxWeightAllowed: 30
  },
  {
    id: "dhl-express-ca",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-ca",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.5,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-ca",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "canadapost-intl",
    company: "Canada Post",
    serviceName: "International Parcel",
    type: "international",
    originCountry: "CA",
    supportedRoutes: ["US", "GB", "AU", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 14 },
    reliabilityScore: 7.8,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.00,
    perAdditionalHalfKgRate: 3.70,
    distanceRate: 1.20,
    maxWeightAllowed: 30
  },

  // ================= AU COURIERS =================
  {
    id: "auspost-parcel-post",
    company: "Australia Post",
    serviceName: "Parcel Post",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.7,
    tags: ["cheapest", "best_value"],
    baseRate: 8.95,
    perAdditionalHalfKgRate: 1.90,
    distanceRate: 0.50,
    maxWeightAllowed: 22
  },
  {
    id: "auspost-express-post",
    company: "Australia Post",
    serviceName: "Express Post",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.3,
    tags: ["fastest", "reliable"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 2.40,
    distanceRate: 0.70,
    maxWeightAllowed: 22
  },
  {
    id: "startrack-premium",
    company: "StarTrack",
    serviceName: "Premium Express",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.4,
    tags: ["fastest", "business_friendly"],
    baseRate: 21.50,
    perAdditionalHalfKgRate: 3.50,
    distanceRate: 0.95,
    maxWeightAllowed: 50
  },
  {
    id: "couriersplease-standard",
    company: "CouriersPlease",
    serviceName: "Standard Parcel",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "ecommerce_friendly"],
    baseRate: 7.95,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 25
  },
  {
    id: "aramex-au-domestic",
    company: "Aramex",
    serviceName: "Domestic Courier",
    type: "domestic",
    originCountry: "AU",
    supportedRoutes: ["AU"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 7.6,
    tags: ["cheapest"],
    baseRate: 8.50,
    perAdditionalHalfKgRate: 1.60,
    distanceRate: 0.45,
    maxWeightAllowed: 30
  },
  {
    id: "dhl-express-au",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-au",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-au",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.3,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "auspost-intl-parcel",
    company: "Australia Post",
    serviceName: "International Standard",
    type: "international",
    originCountry: "AU",
    supportedRoutes: ["US", "CA", "GB", "DE", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 6, max: 12 },
    reliabilityScore: 8.2,
    tags: ["cheapest", "student_friendly"],
    baseRate: 11.20,
    perAdditionalHalfKgRate: 3.80,
    distanceRate: 1.25,
    maxWeightAllowed: 20
  },

  // ================= DE COURIERS =================
  {
    id: "dhl-paket-de",
    company: "DHL",
    serviceName: "Paket",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.4,
    tags: ["most_reliable", "best_value"],
    baseRate: 4.99,
    perAdditionalHalfKgRate: 0.70,
    distanceRate: 0.15,
    maxWeightAllowed: 31.5
  },
  {
    id: "hermes-de",
    company: "Hermes",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 8.1,
    tags: ["cheapest", "student_friendly"],
    baseRate: 3.99,
    perAdditionalHalfKgRate: 0.60,
    distanceRate: 0.10,
    maxWeightAllowed: 25
  },
  {
    id: "dpd-de",
    company: "DPD",
    serviceName: "Classic",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 8.8,
    tags: ["ecommerce_friendly"],
    baseRate: 5.40,
    perAdditionalHalfKgRate: 0.90,
    distanceRate: 0.20,
    maxWeightAllowed: 31.5
  },
  {
    id: "gls-de",
    company: "GLS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "business_friendly"],
    baseRate: 4.80,
    perAdditionalHalfKgRate: 0.85,
    distanceRate: 0.18,
    maxWeightAllowed: 40
  },
  {
    id: "ups-standard-de",
    company: "UPS",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "DE",
    supportedRoutes: ["DE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["fastest", "reliable"],
    baseRate: 8.50,
    perAdditionalHalfKgRate: 1.50,
    distanceRate: 0.40,
    maxWeightAllowed: 50
  },
  {
    id: "dhl-express-de",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.7,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-de",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-de",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.4,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "gls-intl-de",
    company: "GLS",
    serviceName: "International",
    type: "international",
    originCountry: "DE",
    supportedRoutes: ["US", "CA", "GB", "AU", "AE", "IN"],
    features: { tracking: true, insurance: true, pickup: false },
    deliveryDays: { min: 4, max: 8 },
    reliabilityScore: 8.3,
    tags: ["cheapest", "best_value"],
    baseRate: 12.00,
    perAdditionalHalfKgRate: 4.00,
    distanceRate: 1.30,
    maxWeightAllowed: 40
  },

  // ================= AE COURIERS =================
  {
    id: "emirates-post-domestic",
    company: "Emirates Post",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 8.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 2.00,
    distanceRate: 2.50,
    maxWeightAllowed: 35
  },
  {
    id: "aramex-domestic-ae",
    company: "Aramex",
    serviceName: "Domestic Express",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 2 },
    reliabilityScore: 9.2,
    tags: ["reliable", "best_value"],
    baseRate: 19.00,
    perAdditionalHalfKgRate: 3.00,
    distanceRate: 4.00,
    maxWeightAllowed: 30
  },
  {
    id: "shipa-delivery-ae",
    company: "Shipa Delivery",
    serviceName: "Next Day Delivery",
    type: "domestic",
    originCountry: "AE",
    supportedRoutes: ["AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.4,
    tags: ["fastest", "ecommerce_friendly"],
    baseRate: 24.00,
    perAdditionalHalfKgRate: 4.00,
    distanceRate: 5.00,
    maxWeightAllowed: 20
  },
  {
    id: "aramex-intl-ae",
    company: "Aramex",
    serviceName: "International Express",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 6 },
    reliabilityScore: 9.0,
    tags: ["best_value", "regional_specialist"],
    baseRate: 15.00,
    perAdditionalHalfKgRate: 5.00,
    distanceRate: 1.60,
    maxWeightAllowed: 100
  },
  {
    id: "dhl-express-ae",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-ae",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 4 },
    reliabilityScore: 9.3,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-ae",
    company: "UPS",
    serviceName: "Worldwide Saver",
    type: "international",
    originCountry: "AE",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.2,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },

  // ================= IN COURIERS =================
  {
    id: "indiapost-domestic-in",
    company: "India Post",
    serviceName: "Speed Post",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 3, max: 7 },
    reliabilityScore: 8.0,
    tags: ["cheapest", "student_friendly"],
    baseRate: 40.00,
    perAdditionalHalfKgRate: 15.00,
    distanceRate: 8.00,
    maxWeightAllowed: 35
  },
  {
    id: "bluedart-domestic-in",
    company: "Blue Dart",
    serviceName: "Domestic Priority",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 1, max: 3 },
    reliabilityScore: 9.6,
    tags: ["fastest", "premium", "business_friendly"],
    baseRate: 160.00,
    perAdditionalHalfKgRate: 45.00,
    distanceRate: 25.00,
    maxWeightAllowed: 100
  },
  {
    id: "dtdc-domestic-in",
    company: "DTDC",
    serviceName: "Lite / Plus",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.8,
    tags: ["best_value", "reliable"],
    baseRate: 80.00,
    perAdditionalHalfKgRate: 25.00,
    distanceRate: 15.00,
    maxWeightAllowed: 70
  },
  {
    id: "delhivery-domestic-in",
    company: "Delhivery",
    serviceName: "Express",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.9,
    tags: ["ecommerce_friendly"],
    baseRate: 70.00,
    perAdditionalHalfKgRate: 22.00,
    distanceRate: 12.00,
    maxWeightAllowed: 150
  },
  {
    id: "xpressbees-domestic-in",
    company: "XpressBees",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 8.4,
    tags: ["ecommerce_friendly", "cheapest"],
    baseRate: 50.00,
    perAdditionalHalfKgRate: 18.00,
    distanceRate: 10.00,
    maxWeightAllowed: 50
  },
  {
    id: "ecomexpress-domestic-in",
    company: "Ecom Express",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.5,
    tags: ["ecommerce_friendly"],
    baseRate: 55.00,
    perAdditionalHalfKgRate: 19.00,
    distanceRate: 11.00,
    maxWeightAllowed: 50
  },
  {
    id: "shadowfax-domestic-in",
    company: "Shadowfax",
    serviceName: "Express",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 4 },
    reliabilityScore: 8.6,
    tags: ["fastest", "ecommerce_friendly"],
    baseRate: 65.00,
    perAdditionalHalfKgRate: 20.00,
    distanceRate: 12.00,
    maxWeightAllowed: 40
  },
  {
    id: "porter-domestic-in",
    company: "Porter",
    serviceName: "City Courier",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 1, max: 1 },
    reliabilityScore: 9.0,
    tags: ["fastest", "regional_specialist"],
    baseRate: 250.00,
    perAdditionalHalfKgRate: 35.00,
    distanceRate: 150.00,
    maxWeightAllowed: 2000
  },
  {
    id: "professional-domestic-in",
    company: "Professional Couriers",
    serviceName: "Standard",
    type: "domestic",
    originCountry: "IN",
    supportedRoutes: ["IN"],
    features: { tracking: true, insurance: false, pickup: true },
    deliveryDays: { min: 2, max: 6 },
    reliabilityScore: 8.2,
    tags: ["best_value"],
    baseRate: 45.00,
    perAdditionalHalfKgRate: 14.00,
    distanceRate: 9.00,
    maxWeightAllowed: 70
  },
  {
    id: "dhl-express-in",
    company: "DHL",
    serviceName: "Express Worldwide",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 2, max: 5 },
    reliabilityScore: 9.6,
    tags: ["fastest", "most_reliable"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.50,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "fedex-intl-in",
    company: "FedEx",
    serviceName: "International Priority",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 5 },
    reliabilityScore: 9.4,
    tags: ["premium"],
    baseRate: 22.00,
    perAdditionalHalfKgRate: 7.40,
    distanceRate: 2.50,
    maxWeightAllowed: 300
  },
  {
    id: "ups-worldwide-in",
    company: "UPS",
    serviceName: "Worldwide Express",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 3, max: 6 },
    reliabilityScore: 9.3,
    tags: ["business_friendly"],
    baseRate: 21.00,
    perAdditionalHalfKgRate: 7.20,
    distanceRate: 2.40,
    maxWeightAllowed: 300
  },
  {
    id: "aramex-intl-in",
    company: "Aramex",
    serviceName: "International Parcel",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 4, max: 7 },
    reliabilityScore: 8.8,
    tags: ["best_value"],
    baseRate: 14.50,
    perAdditionalHalfKgRate: 4.80,
    distanceRate: 1.60,
    maxWeightAllowed: 100
  },
  {
    id: "garudavega-intl-in",
    company: "Garudavega",
    serviceName: "International",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: true, pickup: true },
    deliveryDays: { min: 5, max: 9 },
    reliabilityScore: 8.7,
    tags: ["regional_specialist", "best_value"],
    baseRate: 12.50,
    perAdditionalHalfKgRate: 4.20,
    distanceRate: 1.40,
    maxWeightAllowed: 150
  },
  {
    id: "indiapost-ems-in",
    company: "India Post",
    serviceName: "EMS Speed Post",
    type: "international",
    originCountry: "IN",
    supportedRoutes: ["US", "CA", "GB", "AU", "DE", "AE"],
    features: { tracking: true, insurance: false, pickup: false },
    deliveryDays: { min: 7, max: 14 },
    reliabilityScore: 7.5,
    tags: ["cheapest", "student_friendly"],
    baseRate: 9.50,
    perAdditionalHalfKgRate: 3.20,
    distanceRate: 1.10,
    maxWeightAllowed: 35
  }
];
